# Generated by Django 4.2.7 on 2023-12-03 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificationName', models.CharField(max_length=200)),
                ('year', models.IntegerField(blank=True)),
                ('url', models.TextField(max_length=1000)),
                ('rollNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internshipName', models.CharField(max_length=200)),
                ('year', models.IntegerField(blank=True)),
                ('duration', models.IntegerField()),
                ('provider', models.CharField(max_length=200)),
                ('status', models.BooleanField()),
                ('url', models.TextField(max_length=1000)),
                ('rollNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=250)),
                ('year', models.IntegerField(blank=True)),
                ('githubUrl', models.TextField(max_length=1000)),
                ('rollNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillName', models.CharField(max_length=100)),
                ('proficiency', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=300)),
                ('gender', models.BooleanField()),
                ('GradCollege', models.CharField(max_length=100)),
                ('GradBranch', models.CharField(max_length=100)),
                ('GradPercentage', models.IntegerField()),
                ('GradYear', models.IntegerField()),
                ('PucCollege', models.CharField(max_length=100)),
                ('PucBranch', models.CharField(max_length=100)),
                ('PucPercentage', models.IntegerField()),
                ('PucYear', models.IntegerField()),
                ('SscCollege', models.CharField(max_length=100)),
                ('SscBranch', models.CharField(max_length=100)),
                ('SscPercentage', models.IntegerField()),
                ('SscYear', models.IntegerField()),
                ('githubProfile', models.TextField(max_length=1000)),
                ('linkedinProfile', models.TextField(max_length=1000)),
                ('address', models.CharField(max_length=200)),
                ('certifications', models.ManyToManyField(to='student.certification')),
                ('internships', models.ManyToManyField(to='student.internship')),
                ('projects', models.ManyToManyField(to='student.project')),
                ('rollNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(to='student.skill')),
            ],
        ),
    ]
