# Generated by Django 4.2.7 on 2023-12-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='GradBranch',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='GradCollege',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='GradPercentage',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='GradYear',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='PucBranch',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='PucCollege',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='PucPercentage',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='PucYear',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='SscBranch',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='SscCollege',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='SscPercentage',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='SscYear',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='about',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='certifications',
            field=models.ManyToManyField(blank=True, to='student.certification'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='githubProfile',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='student',
            name='internships',
            field=models.ManyToManyField(blank=True, to='student.internship'),
        ),
        migrations.AlterField(
            model_name='student',
            name='linkedinProfile',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='student',
            name='projects',
            field=models.ManyToManyField(blank=True, to='student.project'),
        ),
        migrations.AlterField(
            model_name='student',
            name='skills',
            field=models.ManyToManyField(blank=True, to='student.skill'),
        ),
        migrations.AlterField(
            model_name='student',
            name='tagline',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
