# Generated by Django 4.2.7 on 2023-12-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_gradbranch_alter_student_gradcollege_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='GradPercentage',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='GradYear',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='PucCollege',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='PucPercentage',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='PucYear',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='SscPercentage',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='SscYear',
            field=models.IntegerField(null=True),
        ),
    ]
