# Generated by Django 4.2.7 on 2023-12-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_student_gradpercentage_alter_student_gradyear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='GradPercentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='GradYear',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='student',
            name='PucPercentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='PucYear',
            field=models.IntegerField(default=2020),
        ),
        migrations.AlterField(
            model_name='student',
            name='SscPercentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='SscYear',
            field=models.IntegerField(default=2018),
        ),
    ]
