# Generated by Django 4.2.7 on 2023-12-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_student_gradpercentage_alter_student_gradyear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='PucCollege',
            field=models.CharField(default='', max_length=100),
        ),
    ]
