# Generated by Django 4.2.7 on 2023-12-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_student_puccollege'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='about',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
