# Generated by Django 5.0 on 2023-12-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_alter_student_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='expiryDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
