# Generated by Django 5.0 on 2023-12-23 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_alter_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='selected',
            field=models.ManyToManyField(blank=True, related_name='selected', to='student.student'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 23, 10, 0, tzinfo=datetime.timezone.utc)),
        ),
    ]
