# Generated by Django 5.0 on 2023-12-25 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_event_selected_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 25, 10, 0, tzinfo=datetime.timezone.utc)),
        ),
    ]
