# Generated by Django 5.0 on 2023-12-25 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='expiryDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 26, 10, 0, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
