# Generated by Django 5.0 on 2023-12-28 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_alter_event_expirydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 28, 10, 0, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='expiryDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 28, 23, 0, tzinfo=datetime.timezone.utc)),
        ),
    ]
