from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('register', views.signup, name='register'),
    path('login',views.loginView,name='login'),
    path('admin_login',views.admin_login,name='admin_login'),
    path('verify',views.check,name='check'),
    path('home',views.dashboard,name='home'),
    path('logout',views.logoutV,name='logout'),
    path('dashboard/addStudent',views.addStudent,name='addStudent'),
    path('profile',views.profile,name='profile'),
    path('verify/<str:username>',views.verify,name='verify'),
    path('profile/deleteSkill/<int:id>',views.deleteSkill,name='deleteSkill'),
    path('profile/deleteCertification/<int:id>',views.deleteCertification,name='deleteCertification'),
    path('profile/deleteInternship/<int:id>',views.deleteInternship,name='deleteInternship'),
    path('profile/deleteProject/<int:id>',views.deleteProject,name='deleteProject'),
    path('preview',views.preview,name='preview'),
    path('updateEvent/<int:id>',views.updateEvent,name='updateEvent'),
    path('event/<int:eventID>',views.eventStudents,name='eventID'),
    path('deleteEvent/<int:event_id>',views.deleteEvent,name='deleteEvent'),
    path('manageEvents',views.manageEvents,name='manageEvents'),
    path('removeStudent/<int:event_id>/<str:roll_number>',views.removeStudentFromEvent,name='removeStudent'),
    path('sendMail/<int:ID>',views.sendMail,name='sendMail'),
    path('deleteUser/<str:roll_number>',views.deleteUser,name='deleteUser'),
    path('manageStudents',views.manageStudents,name='manageStudents'),
    path('blockUser/<str:roll_number>',views.blockUser,name='blockUser'),
    path('unblockUser/<str:roll_number>',views.unblockUser,name='unblockUser'),
    path('showEvent/<str:event_code>',views.showEvent,name='showEvent'),
    path('profile/<str:event_code>/<str:roll_number>',views.showEvent,name='showEvent'),
    path('showEvent/<str:event_code>/<str:roll_number>',views.showProfile,name='showEvent'),
    path('preview/<str:roll_number>',views.checkStudent,name='checkStudent'),
    path('showEvent/<str:event_code>/ss/<str:roll_number>',views.select_student,name='select_student'),
    path('showEvent/<str:event_code>/ds/<str:roll_number>',views.unselect_student,name='dis_select_student'),
    path('send_report/<str:event_code>/send_report',views.send_report,name='send_report'),
    path('reports',views.reports,name='reports'),

    ]